const FETCH = {
  START: 'FETCH_GOALS_START',
  SUCCESS: 'FETCH_GOALS_SUCCESS',
  FAILURE: 'FETCH_GOALS_FAILURE'
};

const ADD = {
  UPDATE_FIELD: 'GOALS_ADD_UPDATE_FIELD',
  SHOW_MODAL: 'GOALS_ADD_SHOW_MODAL',
  SHOW_SPINNER: 'GOALS_ADD_SHOW_SPINNER',
  RESET: 'GOALS_ADD_RESET',
};

export const GOALS = {
  FETCH,
  ADD,
};
